### ISSUE TITLE
uglify breaks Editor toolbar button in 5.3.0

### ISSUE THREAD

**Issue by Hanl0n** [flibbles/tw5-uglify#9]
I uglified my Wiki and the Editor toolbar broke. 

![Error uglify](https://github.com/flibbles/tw5-uglify/assets/46133714/14372bc8-bc14-4d2d-b290-a1b05fba61a3)

I can reproduce this with 5.3.0 empty.html on Firefox 115.0.1 and Chrome 114.0.5735.199 on Windows 11 Home 22H2. Just uglify any of my TiddlyWiki files or an empty.html and open a Tiddler.

**Comment by flibbles** [comment]
Are you using Uglify 1.6.1 which was released yesterday?

**Comment by Hanl0n** [comment]
I followed this link https://flibbles.github.io/tw5-uglify/uglified.html today.
There is no version displayed but I a link to https://flibbles.github.io/tw5-uglify/ that states 1.6.1 .

**Comment by flibbles** [comment]
Found and isolated. I'll have it fixed later today, maybe tomorrow.

**Comment by flibbles** [comment]
Fixed in version v1.7.0.

Tiddlywiki made ``<$widget attribute=`substitution text` />`` text a thing in V5.3.0, which means backticks had to now be treated specially. Uglify does so now.

**Comment by Hanl0n** [comment]
I tried it on Windows 11 with Firefox, Chrome and Edge.
It is still broken in 1.7.0 and gives the same view when editing a tiddler.

**Comment by flibbles** [comment]
Are you sure? I know exactly what was causing the problem. In the shadow tiddler: `$:/core/ui/EditorToolbar/mono-block`, Uglify was stripping the quotes from around the "```" (triple back-tics), which was causing their new special handling to kick in inapropriately.

I've just confirmed in [v1.7.0 demo site](https://flibbles.github.io/tw5-uglify/#%24%3A%2Fcore%2Fui%2FEditorToolbar%2Fmono-block) that that is not happening anymore, and I'm able to edit tiddlers just fine.

Are you certain you were using the latest version?

**Comment by Hanl0n** [comment]
I just tried again: 

1. I went to https://tiddlywiki.com/#Empty%20Edition and both 
2. clicked the green download button and 
3. followed the link to empty.html an saved the file.
4. went to https://flibbles.github.io/tw5-uglify/uglified.html
5. in both uglified.html I create a New Tiddler wit the + 
 
and they are both broken.

**Comment by flibbles** [comment]
Oh nuts. I forgot to update the wizard. That's my bad.

(I forgot it existed. It's been so long since I've worked on Uglify.)

**Comment by flibbles** [comment]
**Now** it should work if you go through the wizard.

**Comment by Hanl0n** [comment]
Now it works with empty.html and my Wikis.

Thanks
